### ISSUE TITLE
Invalid memory write(UC_ERR_WRITE_UNMAPPED)

### ISSUE THREAD

**Issue by Bee2Kitty** [hooki/configDecoder#1]
errors in decoder.py
19023
Traceback (most recent call last):
  File "decoder.py", line 58, in <module>
    mu.emu_start(code, code + len(MIPS_CODE32))
  File "/home/iot/.local/lib/python2.7/site-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

**Comment by NovusEdge** [comment]
I believe your issue is related to the unicorn package: https://github.com/unicorn-engine/unicorn
